-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: weather_logs
-- Stores historical weather data for cities
create table public.weather_logs (
    id uuid default uuid_generate_v4() primary key,
    city_id text not null,
    city_name text not null,
    temperature numeric,
    day_temp numeric,
    night_temp numeric,
    humidity numeric,
    wind_speed numeric,
    demand_index numeric,
    timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
    source text,
    
    -- Index for faster querying by city and time
    constraint weather_logs_city_id_idx unique (city_id, timestamp)
);

-- Table: alerts
-- Stores alerts generated by the system
create table public.alerts (
    id uuid default uuid_generate_v4() primary key,
    city_id text not null,
    alert_level text not null, -- 'green', 'yellow', 'orange', 'red', 'kerala_special'
    message text,
    recommendation jsonb, -- Store recommendation details as JSON
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    acknowledged boolean default false,
    acknowledged_at timestamp with time zone,
    acknowledged_by text
);

-- Turn on Row Level Security (RLS)
alter table public.weather_logs enable row level security;
alter table public.alerts enable row level security;

-- Create policies (Allow read/write for authenticated users - service role)
-- For simplicity in this demo, we'll allow public read access but restrict write to service role if possible.
-- However, since we are using the python client with a key, we usually use the SERVICE_KEY for writing.
-- Standard policies:
create policy "Enable read access for all users" on public.weather_logs for select using (true);
create policy "Enable insert for authenticated users only" on public.weather_logs for insert with check (true); -- Simplified for demo

create policy "Enable read access for all users" on public.alerts for select using (true);
create policy "Enable insert for authenticated users only" on public.alerts for insert with check (true);
create policy "Enable update for authenticated users only" on public.alerts for update using (true);
